# Generated by Django 3.2 on 2024-03-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quantity',
            new_name='Order',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity_product',
            field=models.IntegerField(default=1),
        ),
    ]
